### ISSUE TITLE
Terraform registry doc: vmc_sddc - connected_accounts

### ISSUE THREAD

**Issue by uprightvinyl** [vmware/terraform-provider-vmc#77] opened 2020-11-17 23:50 UTC
https://registry.terraform.io/providers/vmware/vmc/latest/docs/resources/sddc

The examples use `connected_account_id = data.vmc_connected_accounts.my_accounts.ids[0]`, which generates the following error:

```
Error: Unsupported attribute

  on sddc.tf line 24, in resource "vmc_sddc" "sddc_cloud":
  24:     connected_account_id = data.vmc_connected_accounts.my_accounts.ids[0]

This object has no argument, nested block, or exported attribute named "ids".
Did you mean "id"?
```
`data.vmc_connected_accounts.my_accounts` returns a single value, so the examples should be updated to reflect that.

I would also suggest that the name for the data element be changed from "my_accounts" to "my_account", to better represent that this element creates a value that is a string and not a list.

```
data "vmc_connected_accounts" "my_account" {
  account_number = var.aws_account_number
}

```
Both those changes would result in the following updated block for all examples:
```
  account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0]]
    connected_account_id = data.vmc_connected_accounts.my_account.id
  }
```

**Comment by saloneerege** [comment] 2020-11-18 18:40
Thanks for reporting this issue. This is a duplicate of https://github.com/vmware/terraform-provider-vmc/issues/70 and has already been resolved and merged into the master branch

**Closed as completed by saloneerege** 2020-11-18 18:40 UTC
Labels: documentation
