### ISSUE TITLE
Deploying 2-node or 4-node multiAZ SDDC failing

### ISSUE THREAD

**Issue by Nareshcbit** [vmware/terraform-provider-vmc#168] opened 2023-01-27 14:58 UTC
### Describe the bug

When 2-node or 4-node mutliAZ SDDC are deployed, it is throwing the below error.
Error: for MultiAZ deployment type number of hosts must be atleast 6

VMC supports 2-node and 4-node stretched clusters. 
https://vmc.techzone.vmware.com/vmc-arch/docs/compute/vmc-aws-stretched-cluster

### Reproduction steps

1. Create vmc_sddc resource by setting
num_host = 4 and
customer_subnet_ids = [ ids of 2 subnets ]

Example:

resource "vmc_sddc" "sddc_1" {
....
  num_host            = 4
....
account_link_sddc_config {
    customer_subnet_ids  = [data.vmc_customer_subnets.my_subnets.ids[0],data.vmc_customer_subnets.my_subnets.ids[1]]
    connected_account_id = data.vmc_connected_accounts.my_accounts.id
  }

2. Terraform plan

### Expected behavior

Terraform plan and apply runs successfully.
4-node stretched cluster is deployed in VMC

### Additional context

As VMC supports, many customers are looking for deploying 2-node and 4-node stretched clusters for production workloads.

This is becoming a major road blocker for using terraform to deploy SDDCs

**Comment by carsonpadawon** [comment] 2023-01-30 17:09
I have a customer that is in need of this feature.  Is there an ETA?  This customer is trying to deploy 4 host multiAZ clusters and it is failing.

**Comment by dimitarproynov** [comment] 2023-01-31 14:59
Duplicate of https://github.com/vmware/terraform-provider-vmc/issues/166

The next version of the provider will feature a fix for this issue. As to when the next version will be out: within the next 3 weeks.

Closing.

**Closed as completed by dimitarproynov** 2023-01-31 14:59 UTC
Labels: bug
