### ISSUE TITLE
MinHosts for MULTIAZ deployment

### ISSUE THREAD

**Issue by ravithinknyx** [vmware/terraform-provider-vmc#166] opened 2023-01-27 14:32 UTC
### Describe the bug

The current minimum number of hosts required for deploying MultiAZ is 6 . This is in constants.go . When done manually vmware does allow to create with less number of hosts . Can the limit be reduced so that min hosts can be 1 similar to how we deploy SingleAZ or clusters .

Terraform does not allow deployment with less than 6 hosts . 

### Reproduction steps

1. terraform plan 
2. terraform apply 

Apply fails with minimum required nodes for MultiAZ to be 6 
...

### Expected behavior

Allow MultiAz to be provisioned with less hosts .

https://vmc.techzone.vmware.com/vmc-arch/docs/compute/vmc-aws-stretched-cluster#sec414-sub3

### Additional context

https://github.com/vmware/terraform-provider-vmc/blob/main/vmc/constants/constants.go

// Availability Zones
	SingleAvailabilityZone string = "SingleAZ"
	MultiAvailabilityZone  string = "MultiAZ"
	MinMultiAZHosts        **int    = 6**

**Comment by dimitarproynov** [comment] 2023-02-02 08:38
The fix for the issue is merged. Hopefully, I'll be able to release a new version this week.

**Closed as completed by dimitarproynov** 2023-02-02 08:38 UTC
Labels: bug
