### ISSUE TITLE
Terraform not adding additional hosts to stretched SDDC

### ISSUE THREAD

**Issue by TP-87** [vmware/terraform-provider-vmc#85] opened 2020-12-04 10:27 UTC
Saw the issue when I tried changing the number of hosts in our stretched cluster from 6 to 8. 
 
I saw that this change was correctly picked up as part of the terraform plan/apply 

~ num_host               = 6 -> 8
 
The terraform apply also completed with no errors.
 
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
  Enter a value: yes
 
module.sddc.vmc_sddc.sddc1: Modifying... [id=58733fed-32ee-44bf-81c9-d811426c03db]
module.sddc.vmc_sddc.sddc1: Modifications complete after 1s [id=58733fed-32ee-44bf-81c9-d811426c03db]
 
Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
 
Though the add hosts task was never initiated on the cluster.

I have had to add them in manually via the Gui and the next terraform plan then says was up to date.

**Comment by saloneerege** [comment] 2020-12-04 18:26
Thanks for reporting this issue. We will look into it.

**Comment by saloneerege** [comment] 2020-12-21 23:23
I am not able to reproduce the issue. Closing the issue.

**Closed as completed by saloneerege** 2020-12-21 23:23 UTC
Labels: bug
